---
abstract: 'Define a base URI and then generate variations on it'
author:
  - 'Nic Wolff <nic@angel.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Based
provides:
  URI::Based:
    file: lib/URI/Based.pm
    version: 1.03
requires:
  URI::WithBase: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
